org: alpsilva
app: aws-ha-tier-list-organizer
service: aws-ha-tier-list-organizer
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
